apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-demo
  template:
    metadata:
      labels:
        app: hello-world-demo
    spec:
      containers:
      - name: hello-world-demo
        image: gcr.io/qwiklabs-gcp-03-7154c6c93f6c/helloworld
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-demo
spec:
  type: LoadBalancer
  selector:
    app: hello-world-demo
  ports:
  - port: 80
    targetPort: 8080
