apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: main
        # Replace below with path to your load generator container
        image: gcr.io/...
        env:
        - name: FRONTEND_ADDR
          value: "http://hello-world-demo:80"
        - name: APP_ROUTE
          value: "/"
        # Current configuration will generate 1 RPS per user, per pod
        - name: USERS
          value: "30"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
